
import React, { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'

const About: NextPage = () => {
  const [count, setCount] = useState(0)

    return  (
        
      <>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <p>Count: {count}</p>
        <button onClick={() => setCount(count + 1)}>Increase</button>
      </>
    )
 }
  
export default About